[project]
name = "2025"
version = "25.05.24"
description = "..."
requires-python = ">=3.13"
dependencies = [
    "autopep8>=2.3.2",
    "boto3>=1.38.23",
    "icalendar>=6.3.1",
    "jinja2>=3.1.6",
    "pylint>=3.3.7",
    "requests[security]>=2.32.3",
]
